const express = require('express');
const cors = require('cors');
const PDFDocument = require('pdfkit');
// Agar aap Google Gemini ya OpenAI use kar rahe hain toh uska package yahan aayega
// const { GoogleGenerativeAI } = require("@google/generative-ai");

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 5000;

// --- 1. AI Analysis Route ---
app.post('/api/check-symptoms', async (req, res) => {
    const { age, gender, symptoms, description } = req.body;

    // AI ko instruction dena ke wo patient ka prompt (Urdu/English) samjhay
    const prompt = `
        You are a highly professional medical AI assistant. 
        Analyze the following patient data:
        Age: ${age}
        Gender: ${gender}
        Selected Symptoms: ${symptoms.join(', ')}
        Patient's Personal Note: "${description}"

        Instructions:
        1. If the patient wrote the note in Urdu/Hindi, respond in that language if requested, but keep the structure professional.
        2. Provide Potential Causes, Recommended Actions, and Urgency Level.
        3. Use a clinical and empathetic tone.
        4. Do NOT use markdown stars (**) in the final JSON response string.
    `;

    try {
        // Yahan AI Model call karein (Example text)
        // const result = await model.generateContent(prompt);
        // const aiResponse = result.response.text();
        
        const aiResponse = "Based on your symptoms of " + symptoms.join(', ') + ", you might be experiencing a common viral infection. Please rest and hydrate. " + (description ? "Regarding your note: " + description : "");

        res.json({ diagnosis: aiResponse });
    } catch (error) {
        console.error("AI Error:", error);
        res.status(500).json({ error: "AI Analysis Failed" });
    }
});

// --- 2. Professional PDF Generation Route ---
app.post('/api/generate-pdf', (req, res) => {
    const { age, gender, symptoms, description, diagnosis } = req.body;

    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    // Stream the PDF
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=HealthXray_Report.pdf');
    doc.pipe(res);

    // --- PROFESSIONAL HEADER ---
    doc.rect(0, 0, 612, 100).fill('#226653');
    doc.fillColor('#ffffff').fontSize(26).text('HealthXray AI', 50, 35);
    doc.fontSize(10).text('Digital Clinical Assessment Report', 50, 68);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 450, 45);

    doc.moveDown(5);

    // --- PATIENT DETAILS TABLE ---
    doc.fillColor('#1e2f4a').fontSize(14).text('Patient Information', 50, 120);
    
    // Table Box
    doc.rect(50, 140, 500, 70).stroke('#e2e8f0');
    doc.fillColor('#333').fontSize(11);
    doc.text(`Age: ${age}`, 70, 155);
    doc.text(`Gender: ${gender}`, 200, 155);
    doc.text(`Symptoms: ${symptoms.join(', ')}`, 70, 180, { width: 460 });

    // --- CLINICAL ANALYSIS SECTION ---
    doc.moveDown(5);
    doc.fillColor('#226653').fontSize(14).text('AI Diagnostic Insights', { underline: true });
    doc.moveDown();
    
    // Content Alignment
    doc.fillColor('#2c3e50').fontSize(11).text(diagnosis, {
        align: 'justify',
        lineGap: 5
    });

    if (description) {
        doc.moveDown();
        doc.fillColor('#64748b').fontSize(10).text(`Patient's Additional Note: ${description}`, { italic: true });
    }

    // --- PROFESSIONAL FOOTER ---
    const bottomY = 750;
    doc.rect(0, 780, 612, 62).fill('#f8fafc');
    
    doc.fillColor('#226653').fontSize(10).text('HealthXray - Powered by Advanced AI', 50, 795);
    doc.fillColor('#64748b').fontSize(9);
    doc.text('Email: healthxray14@gmail.com', 50, 810);
    doc.text('Web: https://healthxray.online', 50, 822);
    
    doc.fillColor('#ef4444').fontSize(8).text(
        'DISCLAIMER: This report is generated by AI and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.', 
        280, 795, { width: 280, align: 'right' }
    );

    doc.end();
});

app.listen(PORT, () => {
    console.log(`HealthXray Server running on port ${PORT}`);
});
